"""Shell 命令白名单规则定义 - 纯数据"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from src.types import RiskLevel


@dataclass
class CommandRule:
    """命令规则定义"""

    base_command: str  # 基础命令，如 "docker"
    subcommand: Optional[str] = None  # 子命令，如 "ps"（None 表示匹配所有子命令）
    risk_level: RiskLevel = "safe"  # 风险等级
    blocked_flags: Optional[list[str]] = None  # 禁止的参数，如 ["-rf", "--force"]
    description: str = ""  # 规则描述


# 命令白名单定义
# 规则优先级：更具体的规则优先（有 subcommand > 无 subcommand）
COMMAND_WHITELIST: list[CommandRule] = [
    # ========== 文件系统（只读）==========
    CommandRule("ls", risk_level="safe", description="列出目录内容"),
    CommandRule("ll", risk_level="safe", description="列出目录详情"),
    CommandRule("cat", risk_level="safe", description="查看文件内容"),
    CommandRule("head", risk_level="safe", description="查看文件头部"),
    CommandRule("tail", risk_level="safe", description="查看文件尾部"),
    CommandRule("less", risk_level="safe", description="分页查看文件"),
    CommandRule("more", risk_level="safe", description="分页查看文件"),
    CommandRule("wc", risk_level="safe", description="统计行数/字数"),
    CommandRule("file", risk_level="safe", description="查看文件类型"),
    CommandRule("stat", risk_level="safe", description="查看文件状态"),
    CommandRule("test", risk_level="safe", description="测试路径/条件"),
    CommandRule(
        "find", risk_level="safe", blocked_flags=["-delete", "-exec"], description="查找文件"
    ),
    CommandRule("locate", risk_level="safe", description="快速定位文件"),
    CommandRule("which", risk_level="safe", description="查找命令路径"),
    CommandRule("whereis", risk_level="safe", description="查找命令位置"),
    CommandRule("readlink", risk_level="safe", description="读取符号链接"),
    CommandRule("realpath", risk_level="safe", description="获取真实路径"),
    # ========== 文本处理（只读）==========
    CommandRule("grep", risk_level="safe", description="文本搜索"),
    CommandRule("egrep", risk_level="safe", description="扩展正则搜索"),
    CommandRule("fgrep", risk_level="safe", description="固定字符串搜索"),
    CommandRule("awk", risk_level="safe", description="文本处理"),
    CommandRule(
        "sed", risk_level="safe", blocked_flags=["-i"], description="流编辑器（禁止原地修改）"
    ),
    CommandRule("sort", risk_level="safe", description="排序"),
    CommandRule("uniq", risk_level="safe", description="去重"),
    CommandRule("cut", risk_level="safe", description="列切割"),
    CommandRule("tr", risk_level="safe", description="字符转换"),
    CommandRule("diff", risk_level="safe", description="文件比较"),
    CommandRule("comm", risk_level="safe", description="文件比较"),
    CommandRule("tee", risk_level="medium", description="同时输出到文件和标准输出"),
    # ========== 系统信息（只读）==========
    CommandRule("df", risk_level="safe", description="磁盘使用情况"),
    CommandRule("du", risk_level="safe", description="目录大小"),
    CommandRule("free", risk_level="safe", description="内存使用情况"),
    CommandRule("top", risk_level="safe", description="进程监控"),
    CommandRule("htop", risk_level="safe", description="交互式进程监控"),
    CommandRule("ps", risk_level="safe", description="进程列表"),
    CommandRule("pgrep", risk_level="safe", description="进程搜索"),
    CommandRule("lsof", risk_level="safe", description="打开文件列表"),
    CommandRule("netstat", risk_level="safe", description="网络状态"),
    CommandRule("ss", risk_level="safe", description="套接字状态"),
    CommandRule("ip", risk_level="safe", description="网络配置查看"),
    CommandRule("ifconfig", risk_level="safe", description="网络接口配置"),
    CommandRule("hostname", risk_level="safe", description="主机名"),
    CommandRule("uname", risk_level="safe", description="系统信息"),
    CommandRule("uptime", risk_level="safe", description="运行时间"),
    CommandRule("whoami", risk_level="safe", description="当前用户"),
    CommandRule("id", risk_level="safe", description="用户ID信息"),
    CommandRule("w", risk_level="safe", description="登录用户"),
    CommandRule("who", risk_level="safe", description="登录用户"),
    CommandRule("last", risk_level="safe", description="登录历史"),
    CommandRule("date", risk_level="safe", description="日期时间"),
    CommandRule("cal", risk_level="safe", description="日历"),
    CommandRule("env", risk_level="safe", description="环境变量"),
    CommandRule("printenv", risk_level="safe", description="打印环境变量"),
    CommandRule("echo", risk_level="safe", description="输出文本"),
    CommandRule("printf", risk_level="safe", description="格式化输出"),
    CommandRule("open", risk_level="medium", description="打开应用或文件（如 Docker Desktop）"),
    CommandRule("pwd", risk_level="safe", description="当前目录"),
    CommandRule("history", risk_level="safe", description="命令历史"),
    CommandRule("dmesg", risk_level="safe", description="内核消息"),
    CommandRule("lscpu", risk_level="safe", description="CPU信息"),
    CommandRule("lsmem", risk_level="safe", description="内存信息"),
    CommandRule("lsblk", risk_level="safe", description="块设备信息"),
    CommandRule("lspci", risk_level="safe", description="PCI设备"),
    CommandRule("lsusb", risk_level="safe", description="USB设备"),
    # ========== 网络工具（只读）==========
    CommandRule("ping", risk_level="safe", description="网络连通性测试"),
    CommandRule("curl", risk_level="safe", description="HTTP 请求"),
    CommandRule("wget", risk_level="medium", description="下载文件"),
    CommandRule("dig", risk_level="safe", description="DNS 查询"),
    CommandRule("nslookup", risk_level="safe", description="DNS 查询"),
    CommandRule("host", risk_level="safe", description="DNS 查询"),
    CommandRule("traceroute", risk_level="safe", description="路由追踪"),
    CommandRule("tracepath", risk_level="safe", description="路由追踪"),
    CommandRule("nc", risk_level="medium", description="网络连接工具"),
    CommandRule("netcat", risk_level="medium", description="网络连接工具"),
    CommandRule("telnet", risk_level="medium", description="远程连接"),
    # ========== Docker 命令 ==========
    CommandRule("docker", "ps", risk_level="safe", description="列出容器"),
    CommandRule("docker", "images", risk_level="safe", description="列出镜像"),
    CommandRule("docker", "logs", risk_level="safe", description="查看日志"),
    CommandRule("docker", "inspect", risk_level="safe", description="查看详情"),
    CommandRule("docker", "stats", risk_level="safe", description="资源统计"),
    CommandRule("docker", "top", risk_level="safe", description="容器进程"),
    CommandRule("docker", "port", risk_level="safe", description="端口映射"),
    CommandRule("docker", "diff", risk_level="safe", description="文件变更"),
    CommandRule("docker", "history", risk_level="safe", description="镜像历史"),
    CommandRule("docker", "version", risk_level="safe", description="版本信息"),
    CommandRule("docker", "info", risk_level="safe", description="系统信息"),
    CommandRule("docker", "network", risk_level="safe", description="网络信息"),
    CommandRule("docker", "volume", risk_level="safe", description="卷信息"),
    CommandRule("docker", "exec", risk_level="medium", description="容器内执行命令"),
    CommandRule("docker", "cp", risk_level="medium", description="容器文件复制"),
    CommandRule("docker", "start", risk_level="medium", description="启动容器"),
    CommandRule("docker", "stop", risk_level="medium", description="停止容器"),
    CommandRule("docker", "restart", risk_level="medium", description="重启容器"),
    CommandRule("docker", "pause", risk_level="medium", description="暂停容器"),
    CommandRule("docker", "unpause", risk_level="medium", description="恢复容器"),
    CommandRule("docker", "pull", risk_level="medium", description="拉取镜像"),
    CommandRule("docker", "build", risk_level="medium", description="构建镜像"),
    CommandRule("docker", "run", risk_level="high", description="运行容器"),
    CommandRule("docker", "rm", risk_level="high", description="删除容器"),
    CommandRule("docker", "rmi", risk_level="high", description="删除镜像"),
    CommandRule("docker", "kill", risk_level="high", description="强制停止容器"),
    CommandRule("docker", "prune", risk_level="high", description="清理资源"),
    # ========== Docker Compose ==========
    CommandRule("docker-compose", "ps", risk_level="safe", description="列出服务"),
    CommandRule("docker-compose", "logs", risk_level="safe", description="查看日志"),
    CommandRule("docker-compose", "config", risk_level="safe", description="验证配置"),
    CommandRule("docker-compose", "images", risk_level="safe", description="列出镜像"),
    CommandRule("docker-compose", "top", risk_level="safe", description="服务进程"),
    CommandRule("docker-compose", "start", risk_level="medium", description="启动服务"),
    CommandRule("docker-compose", "stop", risk_level="medium", description="停止服务"),
    CommandRule("docker-compose", "restart", risk_level="medium", description="重启服务"),
    CommandRule("docker-compose", "up", risk_level="medium", description="启动所有服务"),
    CommandRule("docker-compose", "pull", risk_level="medium", description="拉取镜像"),
    CommandRule("docker-compose", "build", risk_level="medium", description="构建服务"),
    CommandRule("docker-compose", "down", risk_level="high", description="停止并删除"),
    CommandRule("docker-compose", "rm", risk_level="high", description="删除容器"),
    # ========== Git 命令 ==========
    CommandRule("git", "status", risk_level="safe", description="仓库状态"),
    CommandRule("git", "log", risk_level="safe", description="提交历史"),
    CommandRule("git", "diff", risk_level="safe", description="差异比较"),
    CommandRule("git", "show", risk_level="safe", description="显示对象"),
    CommandRule("git", "branch", risk_level="safe", description="分支列表"),
    CommandRule("git", "remote", risk_level="safe", description="远程仓库"),
    CommandRule("git", "tag", risk_level="safe", description="标签列表"),
    CommandRule("git", "config", risk_level="safe", description="配置信息"),
    CommandRule("git", "ls-files", risk_level="safe", description="跟踪文件"),
    CommandRule("git", "ls-tree", risk_level="safe", description="树对象"),
    CommandRule("git", "blame", risk_level="safe", description="行追溯"),
    CommandRule("git", "shortlog", risk_level="safe", description="简短日志"),
    CommandRule("git", "describe", risk_level="safe", description="描述标签"),
    CommandRule("git", "rev-parse", risk_level="safe", description="解析引用"),
    CommandRule("git", "fetch", risk_level="medium", description="获取远程"),
    CommandRule("git", "pull", risk_level="medium", description="拉取更新"),
    CommandRule("git", "clone", risk_level="medium", description="克隆仓库"),
    CommandRule("git", "checkout", risk_level="medium", description="切换分支"),
    CommandRule("git", "switch", risk_level="medium", description="切换分支"),
    CommandRule("git", "add", risk_level="medium", description="暂存文件"),
    CommandRule("git", "commit", risk_level="medium", description="提交更改"),
    CommandRule("git", "stash", risk_level="medium", description="暂存更改"),
    CommandRule("git", "merge", risk_level="medium", description="合并分支"),
    CommandRule("git", "rebase", risk_level="medium", description="变基"),
    CommandRule("git", "push", risk_level="high", description="推送到远程"),
    CommandRule(
        "git",
        "reset",
        risk_level="high",
        blocked_flags=["--hard"],
        description="重置（禁止 --hard）",
    ),
    CommandRule("git", "clean", risk_level="high", description="清理未跟踪文件"),
    # ========== Systemd 服务管理 ==========
    CommandRule("systemctl", "status", risk_level="safe", description="服务状态"),
    CommandRule("systemctl", "is-active", risk_level="safe", description="是否活跃"),
    CommandRule("systemctl", "is-enabled", risk_level="safe", description="是否启用"),
    CommandRule("systemctl", "list-units", risk_level="safe", description="单元列表"),
    CommandRule("systemctl", "list-unit-files", risk_level="safe", description="单元文件列表"),
    CommandRule("systemctl", "show", risk_level="safe", description="显示属性"),
    CommandRule("systemctl", "cat", risk_level="safe", description="显示配置"),
    CommandRule("journalctl", risk_level="safe", description="查看日志"),
    CommandRule("systemctl", "start", risk_level="medium", description="启动服务"),
    CommandRule("systemctl", "stop", risk_level="medium", description="停止服务"),
    CommandRule("systemctl", "restart", risk_level="medium", description="重启服务"),
    CommandRule("systemctl", "reload", risk_level="medium", description="重载配置"),
    CommandRule("systemctl", "enable", risk_level="high", description="启用服务"),
    CommandRule("systemctl", "disable", risk_level="high", description="禁用服务"),
    CommandRule("systemctl", "mask", risk_level="high", description="屏蔽服务"),
    CommandRule("systemctl", "unmask", risk_level="high", description="取消屏蔽"),
    # ========== 包管理（查询 - 只读）==========
    CommandRule("apt", "list", risk_level="safe", description="列出包"),
    CommandRule("apt", "show", risk_level="safe", description="包详情"),
    CommandRule("apt", "search", risk_level="safe", description="搜索包"),
    CommandRule("apt-cache", risk_level="safe", description="包缓存查询"),
    CommandRule("dpkg", "-l", risk_level="safe", description="列出已安装包"),
    CommandRule("dpkg", "-L", risk_level="safe", description="包文件列表"),
    CommandRule("dpkg", "-s", risk_level="safe", description="包状态"),
    CommandRule("yum", "list", risk_level="safe", description="列出包"),
    CommandRule("yum", "info", risk_level="safe", description="包信息"),
    CommandRule("yum", "search", risk_level="safe", description="搜索包"),
    CommandRule("rpm", "-qa", risk_level="safe", description="列出已安装包"),
    CommandRule("rpm", "-qi", risk_level="safe", description="包信息"),
    CommandRule("rpm", "-ql", risk_level="safe", description="包文件列表"),
    CommandRule("pip", "list", risk_level="safe", description="Python 包列表"),
    CommandRule("pip", "show", risk_level="safe", description="Python 包详情"),
    CommandRule("pip", "freeze", risk_level="safe", description="Python 依赖"),
    CommandRule("pip3", "list", risk_level="safe", description="Python3 包列表"),
    CommandRule("pip3", "show", risk_level="safe", description="Python3 包详情"),
    CommandRule("pip3", "freeze", risk_level="safe", description="Python3 依赖"),
    CommandRule("npm", "list", risk_level="safe", description="Node 包列表"),
    CommandRule("npm", "view", risk_level="safe", description="包详情"),
    CommandRule("npm", "outdated", risk_level="safe", description="过期包"),
    CommandRule("brew", "list", risk_level="safe", description="Homebrew 已安装包"),
    CommandRule("brew", "info", risk_level="safe", description="Homebrew 包信息"),
    CommandRule("brew", "search", risk_level="safe", description="Homebrew 搜索包"),
    CommandRule("brew", "doctor", risk_level="safe", description="Homebrew 诊断"),
    CommandRule("brew", "config", risk_level="safe", description="Homebrew 配置"),
    CommandRule("brew", "outdated", risk_level="safe", description="Homebrew 过期包"),
    CommandRule("dnf", "list", risk_level="safe", description="DNF 列出包"),
    CommandRule("dnf", "info", risk_level="safe", description="DNF 包信息"),
    CommandRule("dnf", "search", risk_level="safe", description="DNF 搜索包"),
    # ========== 包管理（安装/更新/卸载）==========
    CommandRule("brew", "install", risk_level="medium", description="Homebrew 安装包"),
    CommandRule("brew", "uninstall", risk_level="medium", description="Homebrew 卸载包"),
    CommandRule("brew", "upgrade", risk_level="medium", description="Homebrew 升级包"),
    CommandRule("brew", "update", risk_level="medium", description="Homebrew 更新索引"),
    CommandRule("brew", "tap", risk_level="medium", description="Homebrew 添加源"),
    CommandRule("brew", "untap", risk_level="medium", description="Homebrew 移除源"),
    CommandRule("brew", "services", risk_level="medium", description="Homebrew 服务管理"),
    CommandRule("apt", "install", risk_level="medium", description="APT 安装包"),
    CommandRule("apt", "remove", risk_level="medium", description="APT 卸载包"),
    CommandRule("apt", "update", risk_level="medium", description="APT 更新索引"),
    CommandRule("apt", "upgrade", risk_level="medium", description="APT 升级包"),
    CommandRule("apt", "autoremove", risk_level="medium", description="APT 自动清理"),
    CommandRule("apt-get", "install", risk_level="medium", description="APT 安装包"),
    CommandRule("apt-get", "remove", risk_level="medium", description="APT 卸载包"),
    CommandRule("apt-get", "update", risk_level="medium", description="APT 更新索引"),
    CommandRule("apt-get", "upgrade", risk_level="medium", description="APT 升级包"),
    CommandRule("apt-get", "autoremove", risk_level="medium", description="APT 自动清理"),
    CommandRule("yum", "install", risk_level="medium", description="YUM 安装包"),
    CommandRule("yum", "remove", risk_level="medium", description="YUM 卸载包"),
    CommandRule("yum", "update", risk_level="medium", description="YUM 更新包"),
    CommandRule("dnf", "install", risk_level="medium", description="DNF 安装包"),
    CommandRule("dnf", "remove", risk_level="medium", description="DNF 卸载包"),
    CommandRule("dnf", "update", risk_level="medium", description="DNF 更新包"),
    CommandRule("pip", "install", risk_level="medium", description="Python 安装包"),
    CommandRule("pip", "uninstall", risk_level="medium", description="Python 卸载包"),
    CommandRule("pip3", "install", risk_level="medium", description="Python3 安装包"),
    CommandRule("pip3", "uninstall", risk_level="medium", description="Python3 卸载包"),
    CommandRule("npm", "install", risk_level="medium", description="Node 安装包"),
    CommandRule("npm", "uninstall", risk_level="medium", description="Node 卸载包"),
    CommandRule("npm", "update", risk_level="medium", description="Node 更新包"),
    CommandRule("npx", risk_level="medium", description="Node 执行包命令"),
    CommandRule("yarn", "add", risk_level="medium", description="Yarn 安装包"),
    CommandRule("yarn", "remove", risk_level="medium", description="Yarn 卸载包"),
    CommandRule("pnpm", "add", risk_level="medium", description="pnpm 安装包"),
    CommandRule("pnpm", "remove", risk_level="medium", description="pnpm 卸载包"),
    # ========== Kubernetes / 容器编排 ==========
    CommandRule("kubectl", "get", risk_level="safe", description="K8s 查看资源"),
    CommandRule("kubectl", "describe", risk_level="safe", description="K8s 资源详情"),
    CommandRule("kubectl", "logs", risk_level="safe", description="K8s 查看日志"),
    CommandRule("kubectl", "top", risk_level="safe", description="K8s 资源用量"),
    CommandRule("kubectl", "cluster-info", risk_level="safe", description="K8s 集群信息"),
    CommandRule("kubectl", "config", risk_level="safe", description="K8s 配置查看"),
    CommandRule("kubectl", "version", risk_level="safe", description="K8s 版本"),
    CommandRule("kubectl", "api-resources", risk_level="safe", description="K8s API 资源"),
    CommandRule("kubectl", "events", risk_level="safe", description="K8s 事件"),
    CommandRule("kubectl", "exec", risk_level="medium", description="K8s 容器内执行"),
    CommandRule("kubectl", "cp", risk_level="medium", description="K8s 文件复制"),
    CommandRule("kubectl", "port-forward", risk_level="medium", description="K8s 端口转发"),
    CommandRule("kubectl", "scale", risk_level="medium", description="K8s 扩缩容"),
    CommandRule("kubectl", "rollout", risk_level="medium", description="K8s 滚动更新"),
    CommandRule("kubectl", "apply", risk_level="high", description="K8s 应用配置"),
    CommandRule("kubectl", "delete", risk_level="high", description="K8s 删除资源"),
    CommandRule("kubectl", "create", risk_level="medium", description="K8s 创建资源"),
    CommandRule("kubectl", "edit", risk_level="high", description="K8s 编辑资源"),
    CommandRule("kubectl", "patch", risk_level="high", description="K8s 补丁更新"),
    CommandRule("helm", "list", risk_level="safe", description="Helm 发布列表"),
    CommandRule("helm", "status", risk_level="safe", description="Helm 发布状态"),
    CommandRule("helm", "history", risk_level="safe", description="Helm 历史"),
    CommandRule("helm", "show", risk_level="safe", description="Helm Chart 详情"),
    CommandRule("helm", "search", risk_level="safe", description="Helm 搜索"),
    CommandRule("helm", "repo", risk_level="safe", description="Helm 仓库管理"),
    CommandRule("helm", "install", risk_level="medium", description="Helm 安装"),
    CommandRule("helm", "upgrade", risk_level="medium", description="Helm 升级"),
    CommandRule("helm", "rollback", risk_level="medium", description="Helm 回滚"),
    CommandRule("helm", "uninstall", risk_level="high", description="Helm 卸载"),
    # ========== SSH / 远程操作 ==========
    CommandRule("ssh", risk_level="medium", description="SSH 远程连接"),
    CommandRule("scp", risk_level="medium", description="SCP 远程复制"),
    CommandRule("rsync", risk_level="medium", description="Rsync 同步"),
    CommandRule("sftp", risk_level="medium", description="SFTP 文件传输"),
    # ========== 性能监控 ==========
    CommandRule("vmstat", risk_level="safe", description="虚拟内存统计"),
    CommandRule("iostat", risk_level="safe", description="IO 统计"),
    CommandRule("sar", risk_level="safe", description="系统活动报告"),
    CommandRule("mpstat", risk_level="safe", description="CPU 统计"),
    CommandRule("pidstat", risk_level="safe", description="进程统计"),
    CommandRule("iotop", risk_level="safe", description="IO 进程监控"),
    CommandRule("nethogs", risk_level="safe", description="网络流量监控"),
    CommandRule("iftop", risk_level="safe", description="网络接口流量"),
    CommandRule("nmon", risk_level="safe", description="系统性能监控"),
    CommandRule("perf", risk_level="safe", description="性能分析"),
    CommandRule("strace", risk_level="safe", description="系统调用追踪"),
    CommandRule("ltrace", risk_level="safe", description="库调用追踪"),
    CommandRule("tcpdump", risk_level="medium", description="网络抓包"),
    CommandRule("nmap", risk_level="medium", description="网络扫描"),
    # ========== 其他语言运行时 ==========
    CommandRule("ruby", risk_level="medium", description="Ruby 运行"),
    CommandRule("perl", risk_level="medium", description="Perl 运行"),
    CommandRule("php", risk_level="medium", description="PHP 运行"),
    CommandRule("rustc", risk_level="safe", description="Rust 编译器（版本查看）"),
    CommandRule("gcc", risk_level="safe", description="GCC 编译器（版本查看）"),
    CommandRule("g++", risk_level="safe", description="G++ 编译器（版本查看）"),
    CommandRule("clang", risk_level="safe", description="Clang 编译器"),
    CommandRule("dotnet", risk_level="medium", description=".NET 运行"),
    CommandRule("swift", risk_level="medium", description="Swift 运行"),
    CommandRule("deno", risk_level="medium", description="Deno 运行"),
    CommandRule("bun", risk_level="medium", description="Bun 运行"),
    # ========== 文件操作（写入）==========
    CommandRule("touch", risk_level="medium", description="创建空文件"),
    CommandRule("mkdir", risk_level="medium", description="创建目录"),
    CommandRule("cp", risk_level="medium", description="复制文件"),
    CommandRule("mv", risk_level="medium", description="移动文件"),
    CommandRule("ln", risk_level="medium", description="创建链接"),
    CommandRule(
        "rm", risk_level="high", blocked_flags=["-rf", "-fr", "--recursive"], description="删除文件"
    ),
    CommandRule("rmdir", risk_level="medium", description="删除空目录"),
    CommandRule("chmod", risk_level="high", blocked_flags=["-R", "777"], description="修改权限"),
    CommandRule("chown", risk_level="high", blocked_flags=["-R"], description="修改所有者"),
    # ========== 进程管理 ==========
    CommandRule("kill", risk_level="high", blocked_flags=["-9", "-KILL"], description="终止进程"),
    CommandRule("pkill", risk_level="high", description="按名称终止进程"),
    CommandRule("killall", risk_level="high", description="终止所有匹配进程"),
    # ========== 常用服务命令 ==========
    CommandRule("nginx", risk_level="medium", description="Nginx 服务"),
    CommandRule("redis-server", risk_level="medium", description="Redis 服务"),
    CommandRule("redis-cli", risk_level="safe", description="Redis 客户端"),
    CommandRule("mysql", risk_level="safe", description="MySQL 客户端"),
    CommandRule("psql", risk_level="safe", description="PostgreSQL 客户端"),
    CommandRule("mongosh", risk_level="safe", description="MongoDB Shell"),
    CommandRule("mongo", risk_level="safe", description="MongoDB 客户端"),
    CommandRule("node", risk_level="medium", description="Node.js 运行"),
    CommandRule("python", risk_level="medium", description="Python 运行"),
    CommandRule("python3", risk_level="medium", description="Python3 运行"),
    CommandRule("java", risk_level="medium", description="Java 运行"),
    CommandRule("go", risk_level="medium", description="Go 运行"),
    CommandRule("make", risk_level="medium", description="Make 构建"),
    CommandRule("cargo", risk_level="medium", description="Rust Cargo"),
    CommandRule("uv", risk_level="medium", description="Python uv 工具"),
    # ========== 其他常用工具 ==========
    CommandRule("jq", risk_level="safe", description="JSON 处理"),
    CommandRule("yq", risk_level="safe", description="YAML 处理"),
    CommandRule("xargs", risk_level="medium", description="参数传递"),
    CommandRule("tar", risk_level="medium", description="归档工具"),
    CommandRule("gzip", risk_level="medium", description="压缩"),
    CommandRule("gunzip", risk_level="medium", description="解压"),
    CommandRule("zip", risk_level="medium", description="ZIP 压缩"),
    CommandRule("unzip", risk_level="medium", description="ZIP 解压"),
    CommandRule("base64", risk_level="safe", description="Base64 编解码"),
    CommandRule("md5sum", risk_level="safe", description="MD5 校验"),
    CommandRule("sha256sum", risk_level="safe", description="SHA256 校验"),
    CommandRule("openssl", risk_level="safe", description="SSL 工具"),
    CommandRule("ssh-keygen", risk_level="medium", description="SSH 密钥生成"),
    CommandRule("crontab", "-l", risk_level="safe", description="查看定时任务"),
    CommandRule("crontab", "-e", risk_level="high", description="编辑定时任务"),
]

# 绝对禁止的命令（无论如何都不允许）
BLOCKED_COMMANDS: set[str] = {
    "dd",
    "mkfs",
    "fdisk",
    "parted",
    "mount",
    "umount",
    "sudo",
    "su",
    "passwd",
    "useradd",
    "userdel",
    "groupadd",
    "groupdel",
    "visudo",
    "shutdown",
    "reboot",
    "init",
    "poweroff",
    "halt",
    "iptables",
    "firewall-cmd",
    "ufw",
    "nft",
    "eval",
    "exec",
    "source",
    ".",
}

# 危险的 shell 元字符和模式
# 注意：&&、||、>、>>、< 不在此列表中，由专门的函数智能处理：
#   - && / || → split_chain_commands() 拆分后独立检查每个子命令
#   - > / >> / < → check_redirect_safety() 允许安全重定向（2>/dev/null、2>&1）
DANGEROUS_PATTERNS: list[str] = [
    "$(",
    "`",  # 命令替换
    ";",  # 分号命令链接（始终禁止）
    "|",  # 管道（由 check_pipe_safety 单独处理）
    "&",  # 后台执行
    "\\n",
    "\\r",  # 换行注入
    "${",  # 变量展开
    "~",  # 主目录展开
]

# 以 exit code 1 表示"无匹配/条件不满足"的命令（非错误）
# grep/egrep/fgrep: 无匹配行时返回 1
# diff: 文件有差异时返回 1
# test/[: 条件不成立时返回 1
EXIT1_OK_COMMANDS: frozenset[str] = frozenset({
    "grep", "egrep", "fgrep", "diff", "test", "[",
    # 运维常用：无结果时 exit 1 属于正常行为
    "lsof", "pgrep", "pidof", "fuser", "ss", "netstat",
})

# 允许的管道命令（文本处理工具 + 常用管道目标）
ALLOWED_PIPE_COMMANDS: set[str] = {
    "grep",
    "egrep",
    "fgrep",
    "awk",
    "sed",
    "sort",
    "uniq",
    "cut",
    "tr",
    "head",
    "tail",
    "wc",
    "jq",
    "yq",
    "less",
    "more",
    "cat",
    "tee",
    "xargs",
    "base64",
    "kill",  # lsof -ti :8080 | kill
    "rev",
    "column",
}
